version: '3'
services:
  dsw-server:
    image: datastewardshipwizard/wizard-server:3.24.0
    restart: always
    ports:
      - 127.0.0.1:${DSW_PORT}:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - ./config/application.yml:/app/config/application.yml:ro

  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db-data/data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2022-08-02T23-59-16Z
    restart: always
    command: server /data --console-address ":9001"
    # (!!) Expose only for debugging locally, externally use HTTPS proxy (see MinIO docs)
    ports:
      - 9000:9000
      - 9001:9001
    # (!!) Change default password
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./s3-data/data:/data